#!/bin/sh

exec 2>&1

# Set soft file limit, due to socket usage
{{#if cfg.runtime.max_open_files ~}}
echo "Setting ulimit: "
ulimit -n
ulimit -n {{cfg.runtime.max_open_files}}
ulimit -n
{{~ /if}}

exec webhook-broadcaster \
  --concourse-url "{{cfg.concourse.url}}" \
  --auth-user "{{cfg.concourse.user}}" \
  --auth-password "{{cfg.concourse.password}}" \
  --listen-addr :{{cfg.port}} \
  --webhook-token "{{cfg.webhook_token}}" \
  --refresh-interval "5m" \
  --webhook-concurrency "20"

